({
    appDir:"../src",   
    dir:"../release", 
    mainConfigFile:"../src/js/config.js", 
    paths:{
        one:"mod/one",
        two:"mod/two",
        three:"mod/three"
    },
    modules:[{  
    	name:"combine",
    	include:[
    		'one',
    		'two'
    	]
	}],
    optimize:"uglify" 
   
})